//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NolekWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentView
    {
        public int EquipmentId { get; set; }
        public System.DateTime EquipmentDateCreated { get; set; }
        public string EquipmentImagePath { get; set; }
        public string EquipmentSerialnumber { get; set; }
        public string EquipmentMainEquipmentNumber { get; set; }
        public bool EquipmentStatus { get; set; }
        public string CategoryName { get; set; }
        public string EquipmentConfigurationDescription { get; set; }
        public string EquipmentTypeName { get; set; }
        public string EquipmentTypeDescription { get; set; }
    }
}
