//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NolekWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipment()
        {
            this.EquipmentComponents = new HashSet<EquipmentComponent>();
            this.Customers = new HashSet<Customer>();
        }
    
        public int EquipmentId { get; set; }
        public System.DateTime EquipmentDateCreated { get; set; }
        public string EquipmentImagePath { get; set; }
        public int EquipmentTypeID { get; set; }
        public string EquipmentSerialnumber { get; set; }
        public string EquipmentMainEquipmentNumber { get; set; }
        public int EquipmentConfigurationID { get; set; }
        public bool EquipmentStatus { get; set; }
        public int EquipmentCategoryId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentComponent> EquipmentComponents { get; set; }
        public virtual EquipmentCategory EquipmentCategory { get; set; }
        public virtual EquipmentConfiguration EquipmentConfiguration { get; set; }
        public virtual EquipmentType EquipmentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
