//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NolekWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceReport
    {
        public int ServiceReportId { get; set; }
        public int CustomerId { get; set; }
        public string Status { get; set; }
        public int ServiceId { get; set; }
        public string Comment { get; set; }
        public string ComponentName { get; set; }
        public Nullable<System.DateTime> ServiceDate { get; set; }
        public int EquipmentId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Equipment Equipment { get; set; }
        public virtual Service Service { get; set; }
    }
}
