//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NolekWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Technician
    {
        public int TechnicianId { get; set; }
        public int DepartmentId { get; set; }
        public string TechnicianFirstName { get; set; }
        public string TechnicianLastName { get; set; }
        public int LoginId { get; set; }
    
        public virtual Login Login { get; set; }
        public virtual Nolek Nolek { get; set; }
    }
}
